# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

  # putting into commands
  # https://circleci.com/docs/concepts/

commands:
  build_capnproto:
    steps:
      - restore_cache:
          key: &capnproto-cache capnproto-cache-{{ .Environment.CACHE_VERSION }}-{{ .Environment.MACHINE_OS }}-{{ .Environment.MACHINE_ARCH }}-{{ .Environment.CAPNPROTO_COMMIT }}
      - run:
          name: Check if capnproto already exist
          command: |
            DIR=~/git/capnproto
            if [[ -d "$DIR" ]]
            then
                echo "$DIR exists on your filesystem."
                circleci-agent step halt
            fi
      - run:
          name: Install Capnproto dependency
          command: |
            git clone https://github.com/capnproto/capnproto.git capnproto
            cd capnproto/c++
            git checkout ${CAPNPROTO_COMMIT}
            git submodule update --init --recursive
            autoreconf -i
            ./configure
            make -j4 # check # skip check for now
            sudo make install
      - save_cache:
          key: *capnproto-cache
          paths:
            - ~/git/capnproto


  build_ecal_common:
    steps:
      - restore_cache:
          key: *capnproto-cache
      - run:
          name: Install Capnproto
          command: |
            cd capnproto/c++
            sudo make install
      - checkout:
          path: ecal-common
      - run:
          name: ecal-common submodule update
          command: |
            git -C ecal-common submodule update --init --recursive
      - run:
          name: Install eCAL dependency
          command: |
            sudo add-apt-repository -y ppa:ecal/ecal-5.11
            sudo apt update
            sudo apt install ecal
      - run:
          name: Install OpenCV Dependencies
          command: |
            sudo apt install libopencv-dev
      - run:
          name: Install third-party dependencies
          command: |
            sudo apt install libeigen3-dev
      - run:
          name: Build ecal_common
          command: |
            gcc -Q --help=target # check gcc flags
            cd ecal-common/cpp
            cmake -S. -Bbuild
            cmake --build build -j4

executors:
  ubuntu2004-amd64: &ubuntu2004-amd64-executor
    machine:
      image: ubuntu-2004:current
    resource_class: large
    working_directory: ~/git
  ubuntu2204-amd64: &ubuntu2204-amd64-executor
    machine:
      image: ubuntu-2204:current
    resource_class: large
    working_directory: ~/git
  ubuntu2004-arm64: &ubuntu2004-arm64-executor
    machine:
      image: ubuntu-2004:current
    resource_class: arm.large
    working_directory: ~/git
  ubuntu2204-arm64: &ubuntu2204-arm64-executor
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large
    working_directory: ~/git

workflows:
  ubuntu2004-amd64:
    jobs:
      - build-capnproto:
          os: ubuntu2004-amd64
          context:
            - amd64
            - ubuntu2004
      - build-ecal-common:
          os: ubuntu2004-amd64
          context:
            - amd64
            - ubuntu2004
          requires:
            - build-capnproto
  ubuntu2204-amd64:
    jobs:
      - build-capnproto:
          os: ubuntu2204-amd64
          context:
            - amd64
            - ubuntu2204
      - build-ecal-common:
          os: ubuntu2204-amd64
          context:
            - amd64
            - ubuntu2204
          requires:
            - build-capnproto
  ubuntu2004-arm64:
    jobs:
      - build-capnproto:
          os: ubuntu2004-arm64
          context:
            - arm64
            - ubuntu2004
      - build-ecal-common:
          os: ubuntu2004-arm64
          context:
            - arm64
            - ubuntu2004
          requires:
            - build-capnproto
  ubuntu2204-arm64:
    jobs:
      - build-capnproto:
          os: ubuntu2204-arm64
          context:
            - arm64
            - ubuntu2204
      - build-ecal-common:
          os: ubuntu2204-arm64
          context:
            - arm64
            - ubuntu2204
          requires:
            - build-capnproto
